//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Szkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klasa()
        {
            this.Uczen = new HashSet<Uczen>();
        }
    
        /// <summary>
        /// Identyfikator klasy
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Rocznik uczniów z danej klasy
        /// </summary>
        public int Rocznik { get; set; }
        /// <summary>
        /// Oznaczenie literowe klasy
        /// </summary>
        public string Litera { get; set; }
        /// <summary>
        /// Identyfikator wi¹¿¹cy klasê z jej wychowawc¹
        /// </summary>
        public int Id_Wychowawcy { get; set; }

        /// <summary>
        /// Wychowawca klasy
        /// </summary>
        public virtual Wychowawca Wychowawca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
   
        /// Uczniowie klasy
        public virtual ICollection<Uczen> Uczen { get; set; }

        /// <summary>
        /// Metoda nadpisana do wyœwietlenia klasy w liœcie wszystkich klas.
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return Rocznik + " - " + Litera;
        }
    }
}
