//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Szkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocena
    {
        /// <summary>
        /// Identyfikator oceny
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Wartoœæ liczbowa oceny
        /// </summary>
        public int Ocena1 { get; set; }
        /// <summary>
        /// Identyfikator ucznia, który uzyska³ ocenê
        /// </summary>
        public int Id_Ucznia { get; set; }

        /// <summary>
        /// Na potrzeby wyœwietlania oceny w liœcie ocen ucznia.
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return Ocena1.ToString();
        }
    }
}
