//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Szkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uczen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uczen()
        {
            this.Ocena = new HashSet<Ocena>();
        }
    
        /// <summary>
        /// Identyfikator ucznia
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Imiê ucznia
        /// </summary>
        public string Imie { get; set; }
        /// <summary>
        /// Nazwisko ucznia
        /// </summary>
        public string Nazwisko { get; set; }
        /// <summary>
        /// Identyfikator klasy, do której uczeñ nale¿y
        /// </summary>
        public int Id_Klasy { get; set; }
    
        /// <summary>
        /// Kolekcja ocen ucznia.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocena> Ocena { get; set; }

        /// <summary>
        /// Nadpisano na potrzebê wyœwietlania ucznia w liœcie wszystkich uczniów zadanej klasy.
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return Imie + " " + Nazwisko;
        }
    }
}
